---
abstract: 'Importing XML::Reader using XML::Parsepp'
author:
  - 'Klaus Eichner <klaus03@gmail.com>'
build_requires: {}
configure_requires:
  Module::Build: 0.3
dynamic_config: 1
generated_by: 'Module::Build version 0.3901, CPAN::Meta::Converter version 2.120630'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: XML-Reader-PP
provides:
  XML::Reader::PP:
    file: lib/XML/Reader/PP.pm
    version: 0.02
requires:
  XML::Parsepp: 0.04
  XML::Reader: 0.48
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
